# ----------------------------------------------------------------------------
# GitHub Actions workflow to test building all code samples.
#
# See docs:
# - https://castle-engine.io/github_actions
# - https://docs.github.com/en/actions
# ----------------------------------------------------------------------------

name: Test Code Samples

on: [push, pull_request]

jobs:
  test-fpc:
    name: Test Code Samples with FPC stable
    runs-on: ubuntu-latest
    container: kambi/castle-engine-cloud-builds-tools:cge-none
    steps:
    - uses: actions/checkout@v4
    - run: make all

  test-fpc331:
    name: Test Code Samples with FPC 3.3.1
    runs-on: ubuntu-latest
    container: kambi/castle-engine-cloud-builds-tools:cge-none-fpc331
    steps:
    - uses: actions/checkout@v4
    - run: make all-fpc331
